name : Multiverse CI/CD Workflow 

on:

  push:
    pull_request:
      types: [approved, opened, edited, reopened]
    workflow_dispatch:
  jobs:
  pytest:
    name: Testing workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repository
    uses: actions/checkout@v4

    - name: Update pip
    run: python -m pip install --upgrade pip

    - name: Install Pytest
    run: pip install pytest pytest-cov

    - name: Run Pytest
    run: pytest